name: Tagbot
on: [pull_request]

jobs:
  tagbot:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Git get
      run: |
          pip install git

    - name: Tag shit
      run: |
          python .github/workflows/tagbot.py

